### ISSUE TITLE
useTranslation codemod

### ISSUE THREAD

**Issue by sibelius** [sibelius/ast-i18n#23]
related to #22 
```jsx
import { useTranslation } from 'react-i18next';
```

- [x] add useTranslation import if the component using i18n but it has not imported yet
- [x] add useTranslation hook only on functional components
- [ ] handle both functions and classes

Example

before:
```jsx
import React from 'react';

const Simple = () => (
  <span>My simple text</span>
);
```

after

```jsx
import React from 'react';
import { useTranslation } from 'react-i18next';

const Simple = () => {
   const { t } = useTranslation();

  return (
      <span>{t('my_simple_text')}</span>
   );
}

export default Simple;
```

**Comment by sibelius** [comment]
check this https://github.com/reactjs/react-codemod

- [ ] find react component render method
- [ ] modify them

**Comment by katilius** [comment]
@sibelius  do you think this could be closed?
