### ISSUE TITLE
handle Yup required

### ISSUE THREAD

**Issue by sibelius** [sibelius/ast-i18n#24]
```jsx
withFormik<Props, Values>({
    mapPropsToValues: () => ({}),
    validationSchema: Yup.object().shape({
      type: Yup.string().required('Title is required'),
    }),
    handleSubmit: () => {},
  })(MyForm),
````

is there a patter matching for tree structures? 

I'd like a node like this Yup.**.required

**Comment by guilhermedecampo** [comment]
Did you see thats possible to have locale in yup?

https://github.com/jquense/yup/blob/master/README.md#using-a-custom-locale-dictionary

**Comment by sibelius** [comment]
this could be integrate close to react-i18next solution
