### ISSUE TITLE
Improve stableString

### ISSUE THREAD

**Issue by eveningkid** [sibelius/ast-i18n#25]
Referring to this line comment, https://github.com/sibelius/ast-i18n/blob/master/src/__test__/stableString.test.ts#L27

Maybe it would be simpler to use a package that gets a slug from a string instead, so that it covers all weird use cases already. What do you think @sibelius?

https://www.npmjs.com/package/slugify
Try it at https://npm.runkit.com/slugify

Note: turned out that when trying with the following:
```js
slugify('éé-×', '_') // returns "ee-"
```
Then maybe just inspire your code from their code instead.

**Comment by sibelius** [comment]
tks for the suggestion

we can add the `slugify`to our pipeline of key transformer

I've improvement this stable string idea running in our internal codebase
